name: Transtore Sync

on:
  schedule:
    # - cron: "*/3 * * * *" # mỗi 3 phút
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository }}/backend
          tags: |
            type=sha,enable=true,suffix=,format=short
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          platforms: linux/amd64
  run:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ${{ needs.build.outputs.image }}
    steps:
      - name: Run Transtore
        run: |
          /root/main \
            "${{ secrets.TRANSTORE_PARTNER_TOKEN }}" \
            "gid://partners/App/14548697089" \
            "2663445"
