name: Build Release
on:
  push:
    tags:        
      - v1.*    # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Generate build ID
        id: prep
        run: |
            
            branch=${GITHUB_REF#refs/heads/}
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
            echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}" 
            
            tags=${GITHUB_REF#refs/tags/}
            echo "::set-output name=BUILD_ID::${tags}"   
            echo $tags


      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          env 
