name: Build Release
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - master
    # Sequence of patterns matched against refs/tags
    tags:        
      - v1.*           # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Generate build ID
        id: prep
        run: |
            
            branch=${GITHUB_REF#refs/heads/}
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
            echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"   

