name: Scheduled Jobs Full Test
run-name: Scheduled Job Full Test ${{ github.workflow }}

on:
  schedule:
    - cron: '*/3 * * * *'  # Test chạy mỗi 3 phút
    - cron: '*/5 * * * *'  # Shopify Partner Sync - every 5 minutes (theo file bạn)
    - cron: '*/8 * * * *'  # Gmail Watch - every 8 minutes (theo file bạn)
    - cron: '6 0 * * *'    # Gmail Watch - daily at 06:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Binary
    timeout-minutes: 10
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository }}/backend
          tags: |
            type=sha,enable=true,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  sync-apps:
    needs: build
    runs-on: ubuntu-latest
    name: Shopify Sync Steps
    timeout-minutes: 15
    container:
      image: ${{ needs.build.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Transtore (*/3)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/3 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.TRANSTORE_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Gelacy (*/3)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/3 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.GELACY_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Convercy (*/3)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/3 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.CONVERCY_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Trustz (*/3)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/3 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.TRUSTZ_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Amote (*/3)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/3 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.AMOTE_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Vairo (*/3)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/3 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.VAIRO_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Lavar (*/3)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/3 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.LAVAR_PARTNER_TOKEN }}

  watch-apps:
    needs: build
    runs-on: ubuntu-latest
    name: Gmail Watch Steps
    timeout-minutes: 10
    container:
      image: ${{ needs.build.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Transtore (6 0)
        uses: ./.github/actions/shopify-run
        with:
          cron: '6 0 * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.TRANSTORE_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Gelacy (*/5)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/5 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.GELACY_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Convercy (6 0)
        uses: ./.github/actions/shopify-run
        with:
          cron: '6 0 * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.CONVERCY_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Trustz (*/5)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/5 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.TRUSTZ_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Amote (*/5)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/5 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.AMOTE_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Vairo (*/5)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/5 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.VAIRO_PARTNER_TOKEN }}
      - uses: actions/checkout@v4
      - name: Lavar (*/5)
        uses: ./.github/actions/shopify-run
        with:
          cron: '*/5 * * * *'
          app_id: '14548697089'
          partner_id: '2663445'
          app_token: ${{ secrets.LAVAR_PARTNER_TOKEN }}
